### ISSUE TITLE
Private room – lobby - dupla spymaster ugyanabban a csapatban (nem random esetén)

### ISSUE THREAD

**Issue by holpertadrienn** [Pecske/codenames#10]
Engedi kiválasztani, a már másik játékos által kiválasztott spymaster. 
![cn_szerepválasztás1](https://user-images.githubusercontent.com/66064945/83400199-b9a96e00-a402-11ea-8ce2-146a090d568d.PNG)
![cn_szerepválasztás2](https://user-images.githubusercontent.com/66064945/83400201-ba420480-a402-11ea-8581-08ad94de8d84.PNG)

(Elképzelhető, hogy összefüggésben van az inaktívvá vált játékossal.)

**Comment by Pecske** [comment]
fixed in recent update
