### ISSUE TITLE
Privát szoba lobby -  duplán jeleníti meg az üzenetet

### ISSUE THREAD

**Issue by holpertadrienn** [Pecske/codenames#4]
A privát szoba előkészítésekor a chatüzenetek duplán jelennek meg.
![cn_chat_dupla](https://user-images.githubusercontent.com/66064945/83348690-120f3b80-a32f-11ea-9d45-f2bf0ce8b92a.PNG)

**Comment by hudakelza** [comment]
Ezt a probléma jelentkezett még azóta valamikor?

**Comment by holpertadrienn** [comment]
Most ellenőriztem, már jó. :)

**Comment by hudakelza** [comment]
fixed
